ServerRoot "/usr/local"
Listen 31250

LoadModule unixd_module libexec/apache24/mod_unixd.so
LoadModule authz_core_module libexec/apache24/mod_authz_core.so
LoadModule alias_module libexec/apache24/mod_alias.so
LoadModule dir_module libexec/apache24/mod_dir.so
LoadModule mime_module libexec/apache24/mod_mime.so
LoadModule fastcgi_module libexec/apache24/mod_fastcgi.so

Mutex default:/home/studs/s502535/public_html/web/lab2/httpd-root/mutex-dir/
PidFile "/home/studs/s502535/public_html/web/lab2/httpd-root/httpd.pid"
ErrorLog "/home/studs/s502535/public_html/web/lab2/httpd-root/error.log"

ServerName se.ifmo.ru:31250

DocumentRoot "/home/studs/s502535/public_html/web/lab2/httpd-root/static"

<Directory "/home/studs/s502535/public_html/web/lab2/httpd-root/static">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

<IfModule mime_module>
    TypesConfig etc/apache24/mime.types
    AddType text/html .html
    AddType text/css .css
    AddType application/javascript .js
</IfModule>

FastCgiExternalServer "/home/studs/s502535/public_html/web/lab2/httpd-root/fcgi-bin/server.jar" -host localhost:31251
Alias /fcgi-bin/ "/home/studs/s502535/public_html/web/lab2/httpd-root/fcgi-bin/"

<Directory "/home/studs/s502535/public_html/web/lab2/httpd-root/fcgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
